# File-based Netlify configuration
# https://docs.netlify.com/configure-builds/file-based-configuration/

[[headers]]
for = "/*.woff2"
[headers.values]
Access-Control-Allow-Origin = "*"
Content-Type = "font/woff2"